import Head from "next/head";
import React, { useEffect } from "react";
import { useRouter } from "next/router";
import Index from "src/components/Home/Index";
export default function Home() {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Title Techniq</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <div><Index/></div>
      </main>
    </div>
  );
}
